### ISSUE TITLE
Error when using action on ubuntu-24.04 runner `tree: command not found`

### ISSUE THREAD

**Issue by afuetterer** [hynek/build-and-inspect-python-package#123]
Hi,

I just updated a few of my CI workflows to test the new ubuntu-24.04 runner image. Everything seems to be working fine so far, except baipp. 

I get:
```console
/home/runner/work/_temp/e9988dda-50b6-4f3e-8c69-acb0fb4eae2c.sh: line 6: tree: command not found
Error: Process completed with exit code 127.
```
See: https://github.com/afuetterer/oaipmh-scythe/actions/runs/9125209745/job/25090924390#step:3:270

Can you reproduce this or is this is somehow my fault? Of course I can just use ubuntu-22.04 or ubuntu-latest.

**Comment by hynek** [comment]
looks like in noble it’s a separate package https://packages.ubuntu.com/search?keywords=tree&searchon=names&suite=noble&section=all

You can install it yourself as a quick fix for now – I’ll try to fix it, but I’m at PyCon rn.

**Comment by afuetterer** [comment]
Thanks for the feedback, it is not urgent. I can wait for a fix or follow your recommendation.

Enjoy PyCon!

**Comment by rmartin16** [comment]
FWIW, the same issue occurs on macOS...although, I'm thinking this action is intended to only support runners using ubuntu or similar.

**Comment by hynek** [comment]
it is indeed! 
![CleanShot 2024-05-26 at 18 47 40@2x](https://github.com/hynek/build-and-inspect-python-package/assets/41240/27ca8d8e-3c00-4a53-9c00-54081c802532)

**Comment by afuetterer** [comment]
Awesome, thanks.

**Comment by hynek** [comment]
2.6 is tagged and released

**Comment by rmartin16** [comment]
FYI: 
- https://github.com/actions/runner-images/pull/9936

**Comment by afuetterer** [comment]
I guess you can revert the changes then?
