### ISSUE TITLE
Add support for pyroma

### ISSUE THREAD

**Issue by cleder** [hynek/build-and-inspect-python-package#143]
[pyroma](https://github.com/regebro/pyroma) is aimed at giving a rating of how well a Python project complies with the best practices of the Python packaging ecosystem, primarily PyPI, pip, Distribute etc, as well as a list of issues that could be improved.

Having this as part of the action would be a nice to have, but I do not want to mission creep on this repo.

Otherwise, it is [not a big deal](https://github.com/cleder/crepr/blob/develop/.github/workflows/run-all-tests.yml#L76) to run it yourself.

**Comment by hynek** [comment]
Yeah sorry, that one is rather out of scope especially because it's more of a fuzzy scoring thing rather than pass/fail. But yeah as you wrote, we can't just keep adding linters forever – the main mission is to offer easy insight into what people are building. The linters are only a bit on top.
