### ISSUE TITLE
Job summary?

### ISSUE THREAD

**Issue by henryiii** [hynek/build-and-inspect-python-package#16]
Wild idea perhaps, but what about writing a [job summary](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/)?

Something like:

```yaml
  - name: Adding summary
    run: |
      echo '<details><summary>Wheel contents</summary>' >> $GITHUB_STEP_SUMMARY
      echo '```' >> $GITHUB_STEP_SUMMARY
      ... list tree ... >> $GITHUB_STEP_SUMMARY
      echo '```' >> $GITHUB_STEP_SUMMARY
      echo '</details>' >> $GITHUB_STEP_SUMMARY
```

Basically "Show wheel & SDist contents hierarchically, including metadata." could be put into a nice markdown summary instead of (well, in addition to) being injected in the log, with an expandable section for each. Thoughts?

Also, unrelated, you can actually avoid leaking the python activation now (as of setup-python v4.1+). See near the bottom of https://iscinumpy.dev/post/cibuildwheel-2-10-0/ (I need to fix my anchors, way too long).

**Comment by hynek** [comment]
Thanks! I don't know if I'll be able to get to the keyboard to publish / understand what you mean with the activation. Nice to see some else cares about this. ;)
