### ISSUE TITLE
provide a output that lists compatible python versions

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [hynek/build-and-inspect-python-package#43]
often times its nice to have a matrix job for all supported python versions

it would e nice if a optional output for the list of supported github pythons could be provided (as input for a matrix)

**Comment by hynek** [comment]
Could you elaborate more concretely what you have in mind?

**Comment by RonnyPfannschmidt** [comment]
Given python requires and the supported python versions of github, I want a json list of supposedly supported pythons on github, so that they can be used in a matrix

**Comment by hynek** [comment]
Yeah but how and where? Like as an action output similar to `dist`? Can an action return a dict?

**Comment by RonnyPfannschmidt** [comment]
It will need to be a string as far as I understood the limitations of github actions

An output similar to dist should suffice

**Comment by hynek** [comment]
So what you want is to build the package as a first step, get a `supported_pythons` list like `'["3.10", "3.11"]'` back and then somehow pass it into:

```yaml
      matrix:
        python-version: ${{ steps.baipp.outputs.supported_pythons }}
```

or something? How would that work?

**Comment by RonnyPfannschmidt** [comment]
Correct

**Comment by RonnyPfannschmidt** [comment]
Key problem here is not the list of python versions, but the names github uses for the python action

**Comment by RonnyPfannschmidt** [comment]
Relative to the versions available on github for the setup python action

**Comment by webknjaz** [comment]
So it's about something I've been exploring here: https://github.com/tox-dev/workflow/blob/8ca2e60/.github/workflows/tox.yml#L142.
