### ISSUE TITLE
hatch-fancy-pypi-readme cannot find fragment files when run as part of this Action

### ISSUE THREAD

**Issue by kpfleming** [hynek/build-and-inspect-python-package#56]
I may very well have made a silly mistake somewhere, but... I've just adopted this Action (by lifting `pypi-package.yml` from the `attrs` project and eliminating TestPyPI uploads) in a new project, and when the Action runs I get an error that hatch-fancy-pypi-readme can't find the files it is supposed to pull fragments from. I've added debugging to the workflow and the files appear to be there... It's quite odd.

Log from the most recent attempt is [here](https://github.com/kpfleming/jinjanator/actions/runs/5631458007/job/15258424487?pr=5#step:5:173).

**Comment by hynek** [comment]
It's suspect it's these lines:

```toml
[tool.hatch.build.targets.sdist]
include = [
    "src",
    "tests",
]
```

Hatch probably uses the sdist for it and the docs aren't in there. Just remove the whole section and it should work.

**Comment by kpfleming** [comment]
That was definitely the cause, thanks! I didn't remove the section because then the sdist contains all kinds of stuff that doesn't belong in it, but I ensured that everything relevant is there and now the Action completes successfully.

**Comment by hynek** [comment]
Happy to help and thanks for your patronage! 💛

**Comment by kpfleming** [comment]
First release using this workflow is alive: https://pypi.org/project/jinjanator/
