### ISSUE TITLE
check_wheel_contents: TypeError: type 'typing.TypeVar' is not an acceptable base type 

### ISSUE THREAD

**Issue by hugovk** [hynek/build-and-inspect-python-package#65]
Workflows which were passing two days ago are now failing. For example:

```pytb
Run /tmp/baipp/bin/check-wheel-contents /tmp/baipp/dist/*.whl
  /tmp/baipp/bin/check-wheel-contents /tmp/baipp/dist/*.whl
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Traceback (most recent call last):
  File "/tmp/baipp/bin/check-wheel-contents", line 5, in <module>
    from check_wheel_contents.__main__ import main
  File "/tmp/baipp/lib/python3.12/site-packages/check_wheel_contents/__main__.py", line 8, in <module>
    from .checker import NO_CONFIG, WheelChecker
  File "/tmp/baipp/lib/python3.12/site-packages/check_wheel_contents/checker.py", line 8, in <module>
    from .config import Configuration
  File "/tmp/baipp/lib/python3.12/site-packages/check_wheel_contents/config.py", line 7, in <module>
    from pydantic import BaseModel, Field, ValidationError, validator
  File "/tmp/baipp/lib/python3.12/site-packages/pydantic/__init__.py", line 2, in <module>
    from . import dataclasses
  File "/tmp/baipp/lib/python3.12/site-packages/pydantic/dataclasses.py", line 39, in <module>
    from typing_extensions import dataclass_transform
  File "/tmp/baipp/lib/python3.12/site-packages/typing_extensions.py", line 1167, in <module>
    class TypeVar(typing.TypeVar, _DefaultMixin, _root=True):
TypeError: type 'typing.TypeVar' is not an acceptable base type
Error: Process completed with exit code 1.
```
https://github.com/pylast/pylast/actions/runs/6662722508/job/18107501807#step:3:207

Restarting another repo which was successful two days ago: https://github.com/hugovk/tinytext/actions/runs/6640670564/job/18107596971

I've not dug any further yet.

**Comment by hugovk** [comment]
My guess is this is caused by actions/setup-python now using Python 3.12 by default for `3.x`.

**Comment by hynek** [comment]
Ugh it looks like main works, because I've been updating continuously: https://github.com/hynek/build-and-inspect-python-package/actions/runs/6662999546

I'll tag a 1.5.1 and hope that fixes it.

**Comment by hynek** [comment]
oh god pdm changed something this is gonna be a wild morning

**Comment by hynek** [comment]
phew it's fixed but I have probably to revert all my pdm work :(

thanks for the quick report!

**Comment by hugovk** [comment]
Confirmed working with v1.5.2, thanks for the quick fix!

**Comment by hynek** [comment]
Would you mind checking with v1.5.3 too? Should work, but just making sure.

1.5.2 was an emergency release cut from an emergency branch…

1.5.3 is me reworking everything once again.

**Comment by hugovk** [comment]
v1.5.3 also good! 

https://github.com/hugovk/tinytext/actions/runs/6666129949

**Comment by hynek** [comment]
Awesome thank you! My morning would’ve been even worse without your help!

**Comment by hugovk** [comment]
You're welcome! And thank you for this GitHub Action!
