### ISSUE TITLE
Error: no files matched to [**/requirements.txt or **/pyproject.toml]

### ISSUE THREAD

**Issue by nicoddemus** [hynek/build-and-inspect-python-package#76]
Hi,

Recently I started seeing errors in a few repositories like this when using the action:

```
Error: No file in /home/runner/work/pytest-cpp/pytest-cpp matched to [**/requirements.txt or **/pyproject.toml], make sure you have checked out the target repository
```

AFAICT nothing has changed in the repositories significantly, in fact the errors appeared during pre-commit updates.

Is a requirement for projects to always have a `pyproject.toml` in the root now? Or something else?

Links to the failures (all of them are using the latest version, `1.5.3`):

https://github.com/pytest-dev/pytest-cpp/actions/runs/6720286585/job/18263515881?pr=125
https://github.com/gabrielcnr/pytest-datadir/actions/runs/6697263629/job/18196747120?pr=72

**Comment by hynek** [comment]
ah crap I think that's the attempt to use pip caching. i'll push 1.5.4 in a minute.

**Comment by hynek** [comment]
Would you mind testing in one of those projects with a pin to `d3afbdcb2e3582389a03994cd76eb496b951f20c` if it helps? It should, but I'd prefer to not botch another release.

**Comment by nicoddemus** [comment]
Sure, 1min

**Comment by hynek** [comment]
w00t, thanks! I'll release right away.

**Comment by nicoddemus** [comment]
Great, thanks a lot for the lightning fast response!

**Comment by hynek** [comment]
1.5.4 (works as 1.5 and 1) is out – lmk if something still goes wrong :)

**Comment by nicoddemus** [comment]
I can confirm using just `v1.5` works. Thanks again!
