### ISSUE TITLE
`actions/upload-artifact` v4 / v3 thought

### ISSUE THREAD

**Issue by webknjaz** [hynek/build-and-inspect-python-package#79]
_Re: #78_

So with the recent breakages I was looking into wrapping the action and having a compatible API (https://github.com/actions/upload-artifact/issues/472#issuecomment-1859466721) that's probably going to end up being archived.
And one of the ideas was using both v3 and v4 actions and seeing which one succeeds downloading in an `auto` mode with an input for the end-users to force either v3 or v4.

Technically, this action could upload the same artifact twice with v3 and v4. This way, it'd work for the end-users who use either version. Not sure if you'll consider this idea reasonable, but I wanted to share it in case, it's useful.

**Comment by hynek** [comment]
thanks for sharing, but i think i'm good. keeps it simpler and ultimately faster.
