### ISSUE TITLE
pass options to check-wheel-contents

### ISSUE THREAD

**Issue by mdtanker** [hynek/build-and-inspect-python-package#84]
Hi, I've been using this github action for a while and it's been great. I've just added a second package under my `srs/` folder. Now this actions fails with `W009: Wheel contains multiple toplevel library entries:`.  According to [check-wheel-contents](https://pypi.org/project/check-wheel-contents/), this error can be ignored by adding the configuration option `--toplevel <names>`. Is it possible in my `.yml` to include this config option to be pasted to `check-wheel-contents`?

**Comment by hynek** [comment]
This is something you can fix in your pyproject.toml. I do that myself in _attrs_:

```
[tool.check-wheel-contents]
toplevel = ["attr", "attrs"]
```

**Comment by mdtanker** [comment]
ok great, thank you for the info, I'll try that.
