### ISSUE TITLE
Bumping up dependencies in baipp

### ISSUE THREAD

**Issue by trallard** [hynek/build-and-inspect-python-package#93]
I recently noticed that this action's workflows have been failing as the `check` command does not recognise metadata `2.3` (see reported https://github.com/pypa/twine/issues/1059).

As a minimum, it would be good to upgrade `pkginfo` to `pkginfo>=1.10`, as now `hatchling` and others are using `metadata 2.3`, so I anticipate a number of workflows starting to fail.

Also related: https://github.com/pypa/twine/issues/1070

**Comment by hynek** [comment]
That should be fixed by 2.0.2? I ran into the problem myself which is why I pushed it on short notice last week.

**Comment by trallard** [comment]
Hmmm 🤔 ah it's because I had to revert to v1 per my other issue on the artefacts name 😬😬 soz for the noise

**Comment by hynek** [comment]
Can you please check if https://github.com/hynek/build-and-inspect-python-package/releases/tag/1.5.5 fixes it for you until I get around to work on #92?

**Comment by trallard** [comment]
It works perfectly  🎉 thank you for the super quick fix.
